### ISSUE TITLE
Deployment on Linea

### ISSUE THREAD

**Issue by Akaryatrh** [mds1/multicall#108]
### Chain Name

Linea mainnet

### Chain ID

59144

### RPC URL

https://rpc.linea.build

### Block Explorer URL

https://lineascan.io

### Deployment Funds

No

**Comment by Akaryatrh** [comment]
Hi @mds1!

For now bridge is not yet available for Linea mainnet, so do you prefer ETH to be sent and then you'll use the bridge once available, or do you prefer that we handle the conversion ourselves and send LineaETH on deployer address? (again we also need to wait for the bridge to be available).

Thanks a lot for your support 🙂

**Comment by mds1** [comment]
Hi!

> or do you prefer that we handle the conversion ourselves and send LineaETH on deployer address

This approach of sending funds directly to the deploy on Linea would be easier as it saves me from having to bridge/transfer funds myself :)

**Comment by Akaryatrh** [comment]
Thanks a lot for responding so quickly! I'll ping you once funds will be transferred 👍 
cc @croll83

**Comment by Akaryatrh** [comment]
Side question @mds1, would you be ok if Multicall was listed as part of Linea's ecosystem on [linea.build](https://linea.build/) website? If so, would you have a logotype to provide?

**Comment by mds1** [comment]
> would you be ok if Multicall was listed as part of Linea's ecosystem on [linea.build](https://linea.build/) website?

That would be great, thanks!

> If so, would you have a logotype to provide?

Hmm, let me get back to you on that one. I made a (very basic) one for Optimism RPGF, but I've since gotten a new computer and don't have the files here, and the RPGF site seems to have been taken down. I should probably get around to making a canonical logo, but I have terrible design skills 😅 

In the meantime, some alternative options are:
- The original [logo](https://user-images.githubusercontent.com/304108/55666937-320cb180-5888-11e9-907b-48ba66150523.png) from the [MakerDAO version](https://github.com/makerdao/multicall)
- This [tiny favicon](https://raw.githubusercontent.com/mds1/multicall3-frontend/main/public/favicon.ico) from the [frontend](https://github.com/mds1/multicall3-frontend). I can make a bigger version of that if needed

**Comment by Akaryatrh** [comment]
Thanks a lot @mds1!  No rush for the logo and I guess we can also update it once you have a version that pleases you 🙂

**Comment by Akaryatrh** [comment]
@mds1 funds have been transfered 🙂
https://explorer.linea.build/tx/0xd32a34774207a94313439860728f41d473e2135b4720de0ec963d95785a6ea41

Also, you should have received a whitelisted infura key by email (i sent it to the one referenced on your github account) to test Linea mainnet.

**Comment by mds1** [comment]
Done, thanks! I have a few other deploys to do later today/tomorrow and I'll update the `deployments.json` file in this repo afterwards
