### ISSUE TITLE
Deployment on Filecoin

### ISSUE THREAD

**Issue by tzapu** [mds1/multicall#165]
### Chain Name

Filecoin Mainnet

### Chain ID

314

### RPC URL

https://rpc.ankr.com/filecoin

### Block Explorer URL

https://filfox.info/en

### Deployment Funds

Yes

**Comment by tzapu** [comment]
thanks for this, filecoin now has an EVM compatible layer and this would be great to have there
funding tx, https://filfox.info/en/tx/0xf25e6716da0d0a90bb3d4f6799e728af500f3653ee973eb321388599560a93c3?t=4 
let me know if more is needed btw

i tried to deploy it myself using a pre signed tx, but filecoin only takes type 2/eip 1559 txs and as far as i can tell it won t work with the presign
cheers

**Comment by mds1** [comment]
Can you confirm that Filecoin's address computation is the same as the EVM's and therefore will result in the same address? My understanding is that the FVM is fairly different, so just want to double check before deploying

**Comment by eshon** [comment]
@mds1 - Just confirmed with Filecoin core devs: as long as you do a deployment from an Eth 0x account (and not a native Filecoin account) it will result in the same address.

**Comment by eshon** [comment]
Gentle ping on this @mds1 - is it possible for Snapshot to deploy this using your own private key so that it's deployed to the same deterministic create2 address?

Filecoin's EVM doesn't support legacy type 0 Txn's for @tzapu to complete the deployment himself although core devs are discussing adding it in the future to simplify these multi-chain create2 / create2deployer deployment workflows.

**Comment by mds1** [comment]
Done, thanks!

**Comment by tzapu** [comment]
verified it on filfox @mds1  
https://filfox.info/en/address/0xcA11bde05977b3631167028862bE2a173976CA11?t=3
thank you very much
