### ISSUE TITLE
deploy on zkfair

### ISSUE THREAD

**Issue by andrewzhang97** [mds1/multicall#185]
### Chain Name

ZKFair Testnet

### Chain ID

43851

### RPC URL

https://testnet-rpc.zkfair.io

### Block Explorer URL

https://testnet-scan.zkfair.io/

### Deployment Funds

Yes

**Comment by mds1** [comment]
The current balance of the deployer account appears to be too low, which looks like is because chain has a very high gas price:

> You do not have enough USDC in your account to pay for transaction fees on ZKFair Testnet network. Deposit USDC from another account.

The estimated total cost is ~45 USDC, and the deployer has 5 USDC

(I don't know if USDC is actually the right native token, but that's what I got from https://chainlist.org/?search=zkfair&testnets=true)

**Comment by mds1** [comment]
Closing as stale due to no reply
