### ISSUE TITLE
xdc muticall contract address does not work  https://xdcscan.io/txs/0x07471adfe8f4ec553c1199f495be97fc8be8e0626ae307281c22534460184ed1#overview

### ISSUE THREAD

**Issue by GalaxySciTech** [mds1/multicall#278]
### Chain Name

xdc

### Chain ID

50

### RPC URL

https://rpc.xdcrpc.com

### Block Explorer URL

https://xdcscan.io

### Deployment Funds

Yes

**Comment by GalaxySciTech** [comment]
the transaction is error , pls check again https://xdcscan.io/txs/0x07471adfe8f4ec553c1199f495be97fc8be8e0626ae307281c22534460184ed1#overview

**Comment by nitishpatel** [comment]
Facing similar issue can't seem to also do read from contract, IG the contract is not deployed correctly

**Comment by mds1** [comment]
Thanks for reporting this. It looks like a community member attempted to deploy Multicall3, but the transaction failed on both XDC mainnet and testnet, since there is no code at the address:
```
$ cast code 0xca11bde05977b3631167028862be2a173976ca11 -r https://apothem.xdcrpc.com
0x

$ cast code 0xcA11bde05977b3631167028862bE2a173976CA11 -r https://rpc.xdcrpc.com
0x
```

I did not properly verify this deploy before merging in the PR that added it: https://github.com/mds1/multicall/pull/212. 

It seems this chain is not fully EVM compatible given that all gas was used, which is why the deployment transaction failed. On both mainnet and testnet, the deployer account is now at nonce 1:

```
$ cast nonce 0x05f32b3cc3888453ff71b01135b34ff8e41263f2 -r https://apothem.xdcrpc.com
1

$ cast nonce 0x05f32b3cc3888453ff71b01135b34ff8e41263f2 -r https://rpc.xdcrpc.com
1
```

Unfortunately, as described in the README when using the presigned transaction, a failed usage burns the nonce (hence why it's at 1, and not 0) so I cannot properly the contract. As a result you will need to ask the chain developers to place this contract as a predeploy. 

I've also pushed a commit that removes this chain from the deployments list: e0b48cb

Since there is nothing I can here I will close the issue, and I apologize for the confusion here
