### ISSUE TITLE
Add support for Plume Testnet (v2)

### ISSUE THREAD

**Issue by eyqs** [mds1/multicall#324]
Note that Plume is an Arbitrum Orbit chain, so multicall can't be deployed using the pre-signed transaction because the gas limit is too low.

### Chain Name

Plume Testnet

### Chain ID

98864

### RPC URL

https://test-rpc.plumenetwork.xyz

### Block Explorer URL

https://test-explorer.plumenetwork.xyz

### Deployment Funds

Yes

**Comment by mds1** [comment]
Hey, sorry for the delay here. Is this chain EVM equivalent? If so, the fastest way to get this deployed is to use the presigned transaction as described in the README. Just be sure to read that section carefully and test it on a fork with anvil first, to avoid burning the nonce.

Alternatively, if by any chance this chain uses the OP Stack, Multicall3 will already be there as a [preinstall](https://specs.optimism.io/protocol/preinstalls.html) 

Otherwise I should be able to do the next round of Multicall deploys next week

**Comment by eyqs** [comment]
I added the detail to the initial comment that this is an Arbitrum Orbit chain, so I can't deploy with the presigned transaction because the gas limit isn't set high enough.

**Comment by eyqs** [comment]
@mds1 Will you have time to run through these multicall deploys this week?

**Comment by mds1** [comment]
Done, thanks!
