### ISSUE TITLE
Revert reason

### ISSUE THREAD

**Issue by gigamesh** [mds1/multicall#47]
Hey @mds1! Is it possible to get the revert reason from the individual calls if any fail? I'm playing around with ethers.js callStatic to pull out the info but the best I can get so far is which call failed, but not _why_ it failed.

**Comment by mds1** [comment]
It is possible! If the call fails, the `Result.returnData` (or just `returnData` depending on which method) contains the ABI encoded failure reason.

If that reason is an `Error(string)` from a require, you can decode it like this: https://github.com/Uniswap/v3-periphery/blob/6cce88e63e176af1ddb6cc56e029110289622317/contracts/base/Multicall.sol#L16-L23

If it's a panic you can ABI decode the `Panic(uint256)` and map it to an error code. More info here: https://docs.soliditylang.org/en/latest/control-structures.html#error-handling-assert-require-revert-and-exceptions

**Comment by gigamesh** [comment]
Awesome thank you - are custom errors surfaced in `returnData`, or only `require()` error strings?

**Comment by mds1** [comment]
Yep that is correct, custom errors can be decoded basically the same way calldata can be decoded—you know the signature to get the 4 byte selector, and with the signature you know how to decode the rest of the args
