### ISSUE TITLE
Query: why are all aggregate functions `payable`?

### ISSUE THREAD

**Issue by levblanc** [mds1/multicall#49]
Hi,

I'm new to multicall functions, and trying to use it with my own project in Next.js & ethers.js.

With `stateMutability` as `payable`, I got a transaction object as result of calling aggregate functions.
If I want to get the results data, they only way I found is to modify the aggregate function's `stateMutability` to `view` in the ABI file.

May I know why these functions are set as `payable` in the first place? 
I guess users wants the results data more?

OR, did I use it the wrong way? 
If so, what is the correct way for calling aggregate functions with `stateMutability` as `payable`?

Thanks in advance.

**Comment by mds1** [comment]
All functions are not `view` (and therefore are mutable) because there are two uses for this multicall contract: (1) it can be used on-chain to batch multiple calls into a single transaction, or (2) used off-chain to read a lot of data with a single RPC call. Anecdotally, it seems (2) is more common and it sounds like that's what you are using it for.

Because the methods are not `view`, ethers.js thinks you want to send a transaction when calling those methods (and this would be true even if they were not `payable`). But you don't want to send a transaction, you just want to read data. So instead of calling `multicall.aggregate3(calls)`, you can use `multicall.callStatic.aggregate3(calls)` where [`callStatic`](https://docs.ethers.org/v5/single-page/#/v5/api/contract/contract/-%23-contract-callStatic) tells ethers you want to execute this as a staticcall to retrieve the return data and not send a transaction (where`multicall` is your ethers.js contract instance).

Some methods are also `payable` because it saves a _tiny_ amount of gas, as you can read about here: https://github.com/mds1/multicall#gas-golfing-tricks-and-optimizations

Closing this issue, but feel free to ask any more questions here!

**Comment by levblanc** [comment]
Hey @mds1 , 
Thanks a lot for the detailed explanation & linked info! 
I have no further query.
