### ISSUE TITLE
Feat: Add support for batch contract deployment in Multicall

### ISSUE THREAD

**Issue by kevin-fruitful** [mds1/multicall#81]
I'm an open-source developer interested in contributing to the Multicall repository. I've noticed that the current implementation supports batch function calls, which is an excellent feature. I'd like to propose a new feature that allows users to batch the creation of new contracts in addition to function calls.

The primary use case for this feature would be to enable developers to deploy multiple instances of a contract or multiple unrelated contracts within a single transaction, potentially saving gas and simplifying deployment tasks, eliminating the need for separate transaction signatures and nonce management.

I've already explored a few ways to implement this feature, such as modifying the existing Multicall contract or creating a new factory contract pattern. However, before diving into the implementation, I wanted to discuss the idea with the maintainers and community members to gather feedback and gauge interest.

Do you think this feature would be a valuable addition to the Multicall repository? If so, I'd be happy to work on the implementation and submit a pull request for review.

If you have any concerns, alternative suggestions, or insights, please let me know. I look forward to contributing to this project and hearing your thoughts!

**Comment by kevin-fruitful** [comment]
This feature isn't as cool as I thought it would be. Turns out it's more expensive to use a batch method to deploy contracts. https://github.com/kevin-fruitful/multideploy. Sigh!

**Comment by mds1** [comment]
Guessing the reason is because solidity just expands a bunch of memory (which increases gas cost quadratically after a certain point). If you manually manage memory and reset the free memory pointer after each loop iteration then it might be cheaper

Regardless, the Multicall3 contract can be considered frozen since it's already so widely deployed. But you can achieve similar functionality by have multicall call some deployer contract to do the actual deployment

**Comment by mds1** [comment]
Closing per above comment since Multicall3 is frozen at this point
