### ISSUE TITLE
README example for transferFrom

### ISSUE THREAD

**Issue by fopina** [mds1/multicall#87]
I've been doing NFT bulk transfers using https://marketplace.kalao.io/ because the original NFT contract does not have such functionality (only standard `transferFrom`).

I wanted to script these transfers and also avoid kalao contract and I ended up bumping into this contract.

I got it working with web3.py (web3.py directly has no multicall method support, like the ape example in the repo) for read operations/functions which seems to be the most common use for multicall.

Now that I wanted to try to call `transferFrom`, I'm a little worried about all the warnings about people spending our own tokens. Looking at the contract (in my ignorant eyes), as there is no specific `aggregate` for transactions, it does seem that there is no check that `msg.sender` is the actual `from` address.  
Is that why, if approved, it would mean anyone could just use our address in their own transferFrom calls?

What is the correct way to do these batch transfers then?
I saw batch contract writes, but it seems oriented for contracts calling multicall rather than a private-key entity calling it.

**Comment by mds1** [comment]
I'm not familiar with kalao so I don't fully understand what you're trying to do, but here's some information that might help:
- I'm assuming you're using an EOA, because if you had a contract wallet you can just batch call `transferFrom`. But it sounds like Kalao might hold your NFTs in some type of proxy contract for you, so you can do batch operations.
- Batch transfers of NFTs from an EOA are not possible: Each NFT is a different token contract, and from an EOA you'd have to call `transferFrom` on each NFT. You can of course script this, but you'll still send 1 tx per NFT transfer
- To clarify the risk of warnings:
    - No one can `transferFrom` tokens on your behalf unless you `approve` that address to do so
    - Approving an address lets them call `transferFrom` to move tokens for you.
    - If you approved the Multicall contract to spend your tokens, someone can have the Multicall contract call `myNFT.transferFrom(victim, attacker, tokenId)`. This is why you should not approve Multicall3 to spend your tokens from an EOA

If any of that helps or answers your question, let me know which parts in particular so I can update the README

**Comment by fopina** [comment]
I think those are the things I either already knew or understood from the risk of warnings section.

Though I don't understand why you say each NFT is a different `token contract` (as I meant to bulk transfer tokens of the same contract) I do know I cannot bulk transfer them unless the contract explicitly supports them.

But I thought I could use leverage multicall contract for that, wasn't it designed for people to save also on fees rather than just save on infura API calls for read operations?

Or was it originally thought for contracts to use multicall themselves?

In short, my doubt was:
* is there any safe way to use multicall to transfer tokens without approving access to all tokens (from an EOA)?
* if not, would it be easy to add a different method for it? such as the one I mention and would have `msg.sender == from` check on top? that would make it enough to approveAll on the contract right? I suppose it'd have to be on a different contract as `aggregate` in this one would still skip it :) 

Maybe this is clear for everyone else getting to this repository, but maybe adding this to the batch write warning section would make sense. Instead of saying `never approve multicall to use your tokens`, just say never do writes using multicall from an EOA. The first statement makes it sound like there's a possibility to use batch writes without approving... (imo)

**Comment by mds1** [comment]
> Though I don't understand why you say each NFT is a different token contract (as I meant to bulk transfer tokens of the same contract) I do know I cannot bulk transfer them unless the contract explicitly supports them.

Ah ok, I didn't realize you were doing batch transfers from the same contract, though, the second bullet in my above comment still is true in that case (unless the token contract explicitly supports it like you said)

> But I thought I could use leverage multicall contract for that, wasn't it designed for people to save also on fees rather than just save on infura API calls for read operations?
> 
> Or was it originally thought for contracts to use multicall themselves?

An EOA cannot leverage this multicall contract to batch transfer NFTs, unless you gave approval to the multicall contract to transfer your NFTs, then use multicall to batch various `transferFrom` calls. But you almost certainly should not do that from an EOA, because someone can spot your approval then frontrun you to steal the tokens. A contract wallet could use the multicall contract to do this atomically in a single transaction so there is no risk.

> is there any safe way to use multicall to transfer tokens without approving access to all tokens (from an EOA)?

There is not, this is a limitation of EOAs. Batch calls from an EOA for *any* contract are only supported if that contract bakes in support for batch actions.

> if not, would it be easy to add a different method for it? such as the one I mention and would have msg.sender == from check on top? that would make it enough to approveAll on the contract right? I suppose it'd have to be on a different contract as aggregate in this one would still skip it :)

Yea, you should be able write an application-specific version of this multicall contract with a single aggregate method that requires `msg.sender == from` (where `from` is the from arg in `transferFrom`) and that would protect you.

> just say never do writes using multicall from an EOA.

This is not true though, not all write-operations rely on `msg.sender`, and the ones that don't are safe. For example I can use multicall with an EOA to batch-claim airdrops that take a proof and send tokens to the proved address, or batch-poke contracts for some maintenance action

**Comment by fopina** [comment]
Ah true, claims are a good example as they do apply to the contract I'm using as well. Though this one doesn't take any wallet as parameter and uses `msg.sender` for the claim, so it cannot be used via multicall.

Anyway, good point so I don't have anything to add to the README unless you want to add that last comment that did make it clear to me why it could still be used for an EOA 🙇 

Closing it then and thanks once again for the clarification. I'll try to debug that marketplace [contract](https://snowtrace.io/tx/0xfb1423a2c95aad36573a31b17d140146de3647fc9bb9fd5de25435a81f13c7c4) and just use the same method they use there (as I already approved for the website, I hope it is indeed safe haha)

**Comment by fopina** [comment]
@mds1 I still have to digest better the gas golfing techniques you describe and link, but if you have some free minutes, feel free to recommend any low hanging fruit you can spot in [BulkTransfer](https://github.com/fopina/bulktransfer-contract/blob/main/src/BulkTransfer.sol) (as they're somewhat related) 😄 

First contract I'm trying to write, went through apeworx and then foundry to pick a framework and the whole testing setup 🤯
