### ISSUE TITLE
Deployment Request on Scroll Alpha Testnet

### ISSUE THREAD

**Issue by AtelyPham** [mds1/multicall#91]
### Chain Name

Scroll Alpha

### Chain ID

534353 (0x82751)

### RPC URL

https://alpha-rpc.scroll.io/l2

### Block Explorer URL

https://blockscout.scroll.io/

### Deployment Funds

Yes

**Comment by mds1** [comment]
Is scroll EVM-address-compatible, i.e. `create` address computation happens the same way as ethereum mainnet and results in the same address?

**Comment by AtelyPham** [comment]
Yes I think so, because we also deployed our contracts there and they are the same as other EVM-chain-compatible.

**Comment by mds1** [comment]
Can you link me to an example contract deployment to verify, or send test deployment funds to `0xD2553382a60F121d9b1e35cFC9EBF4870FbCC96F` so I can deploy a dummy contract and verify that way?

I need to be 100% sure before using the official deployer account, since once the nonce is used up there's no other options (except Scroll placing the contract there as a precompile, which isn't great to rely on)

**Comment by AtelyPham** [comment]
I've sent `0.3` to this address `0x05f32B3cC3888453ff71B01135B34FF8e41263F2` by following the instruction in the README to deploy the contract. 

Sent `0.2` to `0xD2553382a60F121d9b1e35cFC9EBF4870FbCC96F` (the tx [here](https://blockscout.scroll.io/tx/0xee72425da2f6fea3b2cc12495f5872dd9fc7f63996c8cc2f3142450dc194a959)). Let me know if you need any extra information.

**Comment by mds1** [comment]
Awesome, thanks! I should be able to verify/test and deploy by EOD monday

**Comment by mds1** [comment]
Done, thanks for your patience!
